name: Validation Syntaxe Ansible (CI)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  verification-syntaxe:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Recuperer le code du depot
        uses: actions/checkout@v4

      - name: ⚙️ Installer Ansible sur le robot
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: 🔍 Verifier la syntaxe du Playbook
        run: |
          ansible-playbook -i hosts playbook.yml --syntax-check
